Created the first static draft
maratbyte/epic-to-do-app pull request #3
Opened 2021-05-14 13:10 UTC by maratbyte

Created the basic HTML layout with a touch of CSS styling

2021-05-16 07:06 UTC, maratbyte commented
I've finished the first draft according to your initial specification. The page has some basic styles and logic. Everything seems to work. Although it looks fine on my desktop screen, I suspect it won't on smaller screens. If it proves to be an issue, I'll resolve it next week.

2021-05-17 07:24 UTC, EngiN33R requested changes

2021-05-17 07:24 UTC, EngiN33R commented on scripts/script.js
> +    let value = input.value;
If you won't be changing the value of a variable later, it is usually considered best practice to use `const` instead of `let`. Because of this, it is usually recommended that you use `let` as little as possible.

2021-05-17 07:24 UTC, EngiN33R commented on styles/style.css
> +input[type="checkbox"]:checked + label::before {
Clever!

2021-05-17 07:24 UTC, EngiN33R commented on scripts/script.js
> +append.onclick = function() {
I was going to say this was an unorthodox approach to solving the problem, but it's really just because I'm too used to a certain way of thinking :) Good job on the logic, but it's likely that you will have to change your approach as new requirements come in.

2021-05-17 07:24 UTC, EngiN33R commented on scripts/script.js
> +    del.onclick = function() {
On the whole, it is recommended to use `element.addEventListener('click', (event) => { ... });` instead of `element.onclick` (and other similar event listeners) for better compatibility.

2021-05-18 04:59 UTC, maratbyte commented on styles/style.css
> +input[type="checkbox"]:checked + label::before {
Yeah, those guys at StackOverflow are really clever! :D

2021-05-18 05:07 UTC, maratbyte commented on scripts/script.js
> +    let value = input.value;
Got it. Resolved.

2021-05-18 05:09 UTC, maratbyte commented on scripts/script.js
> +append.onclick = function() {
What exactly are you commenting on here? On the implementation of event handler function?

2021-05-18 05:31 UTC, merged